/** Iconify names (Lucide) — used with <Icon :icon="…" /> */
export const UI_NAV_ICONS = {
  animals: 'lucide:paw-print',
  feed: 'lucide:newspaper',
  learn: 'lucide:book-open',
  marketplace: 'lucide:store',
  contact: 'lucide:mail',
  faq: 'lucide:circle-help',
  more: 'lucide:circle-ellipsis',
} as const

export const UI_ACTION_ICONS = {
  edit: 'lucide:pencil',
  back: 'lucide:arrow-left',
  chevron: 'lucide:chevron-right',
  chevronLeft: 'lucide:chevron-left',
  chevronRight: 'lucide:chevron-right',
  login: 'lucide:log-in',
  logout: 'lucide:log-out',
  user: 'lucide:user',
  users: 'lucide:users',
  search: 'lucide:search',
  pets: 'lucide:cat',
  rotateLeft: 'lucide:rotate-ccw',
  rotateRight: 'lucide:rotate-cw',
  zoomIn: 'lucide:zoom-in',
  zoomOut: 'lucide:zoom-out',
  reset: 'lucide:refresh-cw',
  remove: 'lucide:x',
  star: 'lucide:star',
  store: 'lucide:store',
  heart: 'lucide:heart',
  bookmark: 'lucide:bookmark',
  image: 'lucide:image',
  send: 'lucide:send',
  posts: 'lucide:file-text',
  message: 'lucide:message-circle',
  notifications: 'lucide:bell',
  feedback: 'lucide:megaphone',
} as const
