-- Expand pet species and breed catalog (idempotent for existing DBs).
-- Safe to run after 006_pets.sql; uses ON CONFLICT DO NOTHING.

INSERT INTO pet_species (slug, label) VALUES
  ('guinea_pig', 'Guinea pig'),
  ('ferret', 'Ferret'),
  ('turtle', 'Turtle'),
  ('lizard', 'Lizard'),
  ('fish', 'Fish'),
  ('horse', 'Horse'),
  ('rat', 'Rat'),
  ('mouse', 'Mouse'),
  ('chinchilla', 'Chinchilla'),
  ('pig', 'Pig'),
  ('goat', 'Goat'),
  ('cow', 'Cow'),
  ('sheep', 'Sheep'),
  ('hedgehog', 'Hedgehog'),
  ('sugar_glider', 'Sugar glider')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO pet_breeds (species_id, label)
SELECT s.id, v.label
FROM (VALUES
  ('cat', 'Ragdoll'),
  ('cat', 'Bengal'),
  ('cat', 'Sphynx'),
  ('cat', 'Russian Blue'),
  ('cat', 'Norwegian Forest Cat'),
  ('cat', 'Abyssinian'),
  ('cat', 'Scottish Fold'),
  ('cat', 'American Shorthair'),
  ('cat', 'Birman'),
  ('cat', 'Oriental'),
  ('cat', 'Mixed breed'),
  ('dog', 'Poodle'),
  ('dog', 'Beagle'),
  ('dog', 'Rottweiler'),
  ('dog', 'Border Collie'),
  ('dog', 'Siberian Husky'),
  ('dog', 'Chihuahua'),
  ('dog', 'Pomeranian'),
  ('dog', 'Dachshund'),
  ('dog', 'Boxer'),
  ('dog', 'Doberman'),
  ('dog', 'Australian Shepherd'),
  ('dog', 'Cocker Spaniel'),
  ('dog', 'Shih Tzu'),
  ('dog', 'Yorkshire Terrier'),
  ('dog', 'French Bulldog'),
  ('dog', 'Cavalier King Charles Spaniel'),
  ('dog', 'Mixed breed'),
  ('rabbit', 'Holland Lop'),
  ('rabbit', 'Mini Rex'),
  ('rabbit', 'Lionhead'),
  ('rabbit', 'Flemish Giant'),
  ('rabbit', 'Netherland Dwarf'),
  ('rabbit', 'Angora'),
  ('rabbit', 'Mixed breed'),
  ('bird', 'Budgerigar'),
  ('bird', 'Cockatiel'),
  ('bird', 'Canary'),
  ('bird', 'Lovebird'),
  ('bird', 'Finch'),
  ('bird', 'Conure'),
  ('bird', 'Macaw'),
  ('bird', 'Cockatoo'),
  ('bird', 'African Grey Parrot'),
  ('bird', 'Mixed breed'),
  ('hamster', 'Syrian hamster'),
  ('hamster', 'Roborovski dwarf'),
  ('hamster', 'Campbell dwarf'),
  ('hamster', 'Winter white dwarf'),
  ('hamster', 'Chinese hamster'),
  ('hamster', 'Mixed breed'),
  ('snake', 'Ball python'),
  ('snake', 'Corn snake'),
  ('snake', 'King snake'),
  ('snake', 'Boa constrictor'),
  ('snake', 'Milk snake'),
  ('snake', 'Garter snake'),
  ('snake', 'Other / unknown'),
  ('elephant', 'Asian elephant'),
  ('elephant', 'African bush elephant'),
  ('elephant', 'Other / unknown'),
  ('turtle', 'Red-eared slider'),
  ('turtle', 'Painted turtle'),
  ('turtle', 'Box turtle'),
  ('turtle', 'Map turtle'),
  ('turtle', 'Other / unknown'),
  ('lizard', 'Leopard gecko'),
  ('lizard', 'Bearded dragon'),
  ('lizard', 'Crested gecko'),
  ('lizard', 'Anole'),
  ('lizard', 'Monitor'),
  ('lizard', 'Skink'),
  ('lizard', 'Other / unknown'),
  ('fish', 'Goldfish'),
  ('fish', 'Betta'),
  ('fish', 'Guppy'),
  ('fish', 'Tetra'),
  ('fish', 'Cichlid'),
  ('fish', 'Angelfish'),
  ('fish', 'Koi'),
  ('fish', 'Other / freshwater community'),
  ('horse', 'Thoroughbred'),
  ('horse', 'Quarter Horse'),
  ('horse', 'Arabian'),
  ('horse', 'Pony'),
  ('horse', 'Warmblood'),
  ('horse', 'Draft'),
  ('horse', 'Mixed breed'),
  ('guinea_pig', 'American'),
  ('guinea_pig', 'Abyssinian'),
  ('guinea_pig', 'Peruvian'),
  ('ferret', 'Standard'),
  ('ferret', 'Angora'),
  ('rat', 'Dumbo'),
  ('rat', 'Standard'),
  ('rat', 'Hairless'),
  ('mouse', 'Fancy'),
  ('mouse', 'Feeder-type'),
  ('chinchilla', 'Standard grey'),
  ('chinchilla', 'Mutation colors'),
  ('pig', 'Vietnamese pot-bellied'),
  ('pig', 'Miniature pig'),
  ('pig', 'Other domestic'),
  ('goat', 'Nigerian Dwarf'),
  ('goat', 'Boer'),
  ('goat', 'Pygmy'),
  ('goat', 'Mixed breed'),
  ('cow', 'Holstein'),
  ('cow', 'Jersey'),
  ('cow', 'Angus'),
  ('cow', 'Highland'),
  ('cow', 'Other / mixed'),
  ('sheep', 'Merino'),
  ('sheep', 'Suffolk'),
  ('sheep', 'Dorper'),
  ('sheep', 'Other / mixed'),
  ('hedgehog', 'African pygmy'),
  ('sugar_glider', 'Standard')
) AS v(species_slug, label)
JOIN pet_species s ON s.slug = v.species_slug
ON CONFLICT (species_id, label) DO NOTHING;
